name: MiniPlaceholders-DiamondBank-OG
author: NotAlexNoyle
description: Provides MiniPlaceholders for DiamondBank-OG.
website: https://github.com/true-og/DiamondBank-MiniPlaceholders-OG
version: '${version}'
api-version: '${apiVersion}'
main: plugin.DiamondBankMiniPlaceholdersOG
depend: 
  - DiamondBank-OG
  - Utilities-OG
